### PR TITLE
simplify iteration and avoid making copies

### PR DESCRIPTION
**Pull request by campoy**
Currently, for infix and postfix traversals, any modification to the parent is lost since it's performed on a copy.

This fixes the bug and simplifies the code keeping all iteration logic in a single function.

Signed-off-by: Francesc Campoy <campoy@golang.org>

### CODE REVIEW

**Comment by juanjux** [comment]
I see the solution if better using a map (I used the same solution for the libuast iterators) but I don't understand the bug part, where are the nodes in the stack modified during the traversal?

**Comment by campoy** [comment]
Look at the test, the role `uast.Key` disappears currently when using `infix` or `postfix`

**Comment by juanjux** [comment]
I see. It seems it's not working, the traversal tests are failing (wrong order and duplicates).

**Comment by dennwc** [comment]
This is definitely broken on v2. Also, most of the traversal code is actually in the go-client now. Closing this for now, but feel free to apply to the go-client.

**Pull request closed without merging**
