### PR TITLE
fix typo in documentation link

### PR DESCRIPTION
**Pull request by campoy**

### CODE REVIEW

**Comment by campoy** [comment]
What does this mean, @mcuadros? The `details` link goes to 404 😞

**Comment by mcuadros** [comment]
You need to sing-off the commit. And yes, it points to a CONTRIBUTING.md, file, and is missing. https://github.com/src-d/guide/pull/73

**Comment by mcuadros** [comment]
We really prefer having the `.` even knowing that is not a good practice, The annotations files is a pretty large and [complex files](https://github.com/bblfsh/java-driver/blob/master/driver/normalizer/annotation.go), and we want to avoid the hundreds of repetitions of the package name.

**Comment by abeaumont** [comment]
@campoy while there's no contributing file, you can check [DCO](https://github.com/bblfsh/sdk/blob/master/DCO) for the signed-off check details.

**Comment by campoy** [comment]
updated title and code

**Pull request merged**
