### PR TITLE
Add language to Response and NativeResponse.

### PR DESCRIPTION
**Pull request by juanjux**
Adds the Language field to the responses. Part of #203, combined with server PR   that actually fills the language field.

Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

### CODE REVIEW

**Comment by mcuadros** [comment]
this change will force to update all the fixtures, since the output of the request will be different, right?

**Comment by juanjux** [comment]
@mcuadros I don't think so, since the String() method of the objects, that the fixtures use, doesn't print the language, but I'll update them if needed.

**Comment by juanjux** [comment]
Trough now that you said it... I should update those methods so the language is printed too since is part of the request (and the fixtures). I'll update the PR.

**Comment by mcuadros** [comment]
Then lets remove to the ".source" from the fixtures

**Comment by juanjux** [comment]
@mcuadros that was an AMBUSH.

I've updated this PR to support integration tests without the `.source` and made another PR for the Python driver (that won't work until this is merged, just like the bblfshd PR): https://github.com/bblfsh/python-driver/pull/136

Tomorrow I'll update the Java driver with the renamed fixtures.

**Pull request merged**
