### PR TITLE
move common main function from template to driver package

### PR DESCRIPTION
**Pull request by dennwc**

### CODE REVIEW

**Comment by dennwc** [comment]
Looks like the user profile is gone as well: https://github.com/jteeuwen

**Comment by dennwc** [comment]
@juanjux Is there a script to regenerate all drivers?

**Comment by juanjux** [comment]
I'll search for some fork of go-bindata and fork it inside bblfsh.

No script to regenerate existing drivers since they could have changes but we could do it as we update them for other reasons.

**Comment by juanjux** [comment]
@dennwc I've forked go-bindata to https://github.com/bblfsh/go-bindata could you update the PR to link it?

**Comment by juanjux** [comment]
@dennwc looks like somebody re-registered the account keeping the project so the build should work now without changes, I'll restart it.

**Comment by juanjux** [comment]
@dennwc now it says that the generated bindata is out of sync, can you regenerate it and update the PR?

**Pull request merged**
