### PR TITLE
avoid installation when Go is already installed

### PR DESCRIPTION
**Pull request by campoy**

### CODE REVIEW

**Comment by mcuadros** [comment]
How could be already installed? 

Also as you can read inside of the Dockerfile is copied from:
https://github.com/docker-library/golang/blob/master/1.8/alpine/Dockerfile

And we need to update it to use 1.9, so I don't know if this PR will be used to much.

**Comment by campoy** [comment]
_note_: the link points to a 404

We have `FROM ${DOCKER_BUILD_NATIVE_IMAGE}`, and in my case Go is installed in the native image.
There's a deeper conversation about whether it'd be possible to use multistage dockerfiles soon to avoid this kind of conflicts.

**Comment by smola** [comment]
@dennwc Maybe this is not relevant anymore with the new build system?

**Comment by dennwc** [comment]
Yes, I think so. Closing.

**Pull request closed without merging**
